<!DOCTYPE html>
<html lang="en-US">
<!--********************************************-->
<!--*       Generated from PreTeXt source      *-->
<!--*                                          *-->
<!--*         https://pretextbook.org          *-->
<!--*                                          *-->
<!--********************************************-->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="robots" content="noindex, nofollow">
</head>
<body class="ignore-math">
<h2 class="heading"><span class="type">Paragraph</span></h2>
<p>This is a preemptive warning of a merge conflict and occurs when you are trying to pull in or push out a commit and another commit gets in the way. Git doesn't want to create them, so it refuses to push or pull until you fix something. This is not the same error as in <a href="S_forcemerge.html" class="internal" title="Section C.4: Git Won't Let Me Pull From Upstream or Origin!">SectionÂ C.4</a>, although it is closely related. You might get something like this: <div class="code-box" style="width: 100%; margin-left: 0%; margin-right: 0%;"><pre class="console"><b>git push
</b>To &lt;repo-you-are-pushing-to&gt;.git
 ! [rejected]        main -&gt; main (fetch first)
error: failed to push some refs to '&lt;repo-you-are-pushing-to&gt;.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
</pre></div> This looks kind of scary. Let's see how to fix this.</p>
<span class="incontext"><a href="S_diverge_branch.html#p-1039" class="internal">in-context</a></span>
</body>
</html>
